version: 2.1

jobs:
  oidc-aws:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_DEFAULT_REGION: <your AWS region here>
      AWS_ROLE_ARN: <your role ARN here>
    steps:
      - run:
          name: authenticate-and-interact
          command: |
            # use the OpenID Connect token to obtain AWS credentials
            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
              $(aws sts assume-role-with-web-identity \
              --role-arn ${AWS_ROLE_ARN} \
              --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
              --web-identity-token $CIRCLE_OIDC_TOKEN \
              --duration-seconds 3600 \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
            
            # interact with AWS
            aws sts get-caller-identity
  oidc-gcp:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-cli/install:
          version: "372.0.0"
      - run:
          name: Authenticate with GCP
          command: |
            # STS_TOKEN=$(curl -0 -X POST https://sts.googleapis.com/v1/token \
            #   -H 'Content-Type: text/json' \
            #   -d '{
            #     "audience" : "//iam.googleapis.com/projects/193436206874/locations/global/workloadIdentityPools/oidc_poc/providers/circleci",
            #     "grantType" : "urn:ietf:params:oauth:grant-type:token-exchange",
            #     "requestedTokenType" : "urn:ietf:params:oauth:token-type:access_token",
            #     "scope" : "https://www.googleapis.com/auth/cloud-platform",
            #     "subjectTokenType" : "urn:ietf:params:oauth:token-type:jwt",
            #     "subjectToken" : "$CIRCLE_OIDC_TOKEN"
            #   }'
            # )
            
            curl -0 -X POST https://sts.googleapis.com/v1/token \
              -H 'Content-Type: text/json' \
              -d '{
                "audience" : "//iam.googleapis.com/projects/193436206874/locations/global/workloadIdentityPools/oidc_poc/providers/circleci",
                "grantType" : "urn:ietf:params:oauth:grant-type:token-exchange",
                "requestedTokenType" : "urn:ietf:params:oauth:token-type:access_token",
                "scope" : "https://www.googleapis.com/auth/cloud-platform",
                "subjectTokenType" : "urn:ietf:params:oauth:token-type:jwt",
                "subjectToken" : "$CIRCLE_OIDC_TOKEN"
              }'

            # ACCESS_TOKEN=$(curl -0 -X POST https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/gke-poc@olukotun-demo.iam.gserviceaccount.com:generateAccessToken \
            #     -H 'Content-Type: text/json' \
            #     -H 'Authorization: Bearer $STS_TOKEN' \
            #     -d '{
            #         "scope": ["https://www.googleapis.com/auth/cloud-platform"]
            #     }'
            # )

            # echo $ACCESS_TOKEN >> $BASH_ENV
    
workflows:
  version: 2
  oidc_poc:
    jobs:
      - oidc-aws:
          context: 
            - cloudSecrets
