version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3.0
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.14.1
  gcp-gke: circleci/gcp-gke@1.4.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-cli/install:
          version: "372.0.0"
      # - gcp-gcr/gcr-auth
      # - run: gcloud auth configure-docker --quiet "${GOOGLE_COMPUTE_REGION}-docker.pkg.dev"
      # - gcp-gcr/build-image:
      #     tag: $CIRCLE_SHA1
      #     image: $IMAGE_REPO_NAME/$CIRCLE_PROJECT_REPONAME
      #     registry-url: $IMAGE_HOST_ADDR
      # - gcp-gcr/push-image:
      #     tag: $CIRCLE_SHA1
      #     image: $IMAGE_REPO_NAME/$CIRCLE_PROJECT_REPONAME
      #     registry-url: $IMAGE_HOST_ADDR
      - run:
          name: Build and push image
          command: |
            gcloud auth configure-docker --quiet $IMAGE_HOST_ADDR
            docker build -t "${IMAGE_HOST_ADDR}/${GOOGLE_PROJECT_ID}/${IMAGE_REPO_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" .
            docker push "${IMAGE_HOST_ADDR}/${GOOGLE_PROJECT_ID}/${IMAGE_REPO_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
  deploy:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - gcp-gcr/gcr-auth
      - run: gcloud auth configure-docker --quiet "${GOOGLE_COMPUTE_REGION}-docker.pkg.dev"
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $CLUSTER_NAME
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-name: deployment/$CIRCLE_PROJECT_REPONAME
          resource-file-path: k8s/deployment.yml
          envsubst: true
          show-kubectl-command: true
          get-rollout-status: true
          watch-rollout-status: true
      - run: kubectl get service

workflows:
  version: 2
  production_flow:
    jobs:
      - build-and-push:
          context: cloudSecrets
      - deploy:
          name: deploy-staging
          requires:
            - build-and-push
      # - approve-production:
      #     type: approval
      #     requires:
      #       - deploy-staging
      # - deploy:
      #     name: deploy-production
      #     env: production
      #     requires: 
      #       - approve-production
