apiVersion: apps/v1 
kind: Deployment
metadata:
  name: $CIRCLE_PROJECT_REPONAME
spec:
  selector:
    matchLabels:
      app: $CIRCLE_PROJECT_REPONAME
  replicas: 2
  template:
    metadata:
      labels:
        app: $CIRCLE_PROJECT_REPONAME
    spec:
      containers:
      - name: $CIRCLE_PROJECT_REPONAME
        image: ${IMAGE_HOST_ADDR}/${GOOGLE_PROJECT_ID}/${IMAGE_REPO_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}-service
spec:
  type: LoadBalancer
  selector:
    app: $CIRCLE_PROJECT_REPONAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
